#!/usr/bin/env bash
# Copyright (C) 2026 Jean Yves Beaucamp
# CERN LXPlus ssh connection manager

if [[ ! -z "$CERN_USERNAME" ]]; then
    user="$CERN_USERNAME"
else
    user="$USER"
fi

lxhost_arg=""

do_atlasgw_proxy=false

do_vnc_proxy=false
vnc_port=5907

do_bkg=false

do_kerb_only=false

do_cm_start_only=false
do_cm_exit_only=false
do_cm_exit_all_only=false
do_cm_status_only=false

#------------------------------------------
# Parse cmd line arguments
#------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        -u|--user)
            user="$2"
            shift 2
            ;;
        -p|--p1-proxy)
            do_atlasgw_proxy=true
            shift
            ;;
        -v|--vnc)
            do_vnc_proxy=true
            shift
            ;;
        --vnc=*)
            do_vnc_proxy=true
            offset="${1#--vnc=}"
            vnc_port=$((5900 + $offset))
            shift
            ;;
        -b|--background)
            do_bkg=true
            shift
            ;;
        -k|--kerb)
            do_kerb_only=true
            shift
            ;;
        -c|--cm)
            do_cm_start_only=true
            shift
            ;;
        -e|--cm-exit|--cme)
            do_cm_exit_only=true
            shift
            ;;
        -E|--cm-exit-all)
            do_cm_exit_all_only=true
            do_cm_exit_only=true
            shift
            ;;
        -s|--cm-status|--cms)
            do_cm_status_only=true
            shift
            ;;
        -h|--help)
            echo "Usage: lxp [-u|--user USER] [-p|--p1-proxy] [-v|--vnc[=OFFSET]] [-b|--background] [-k|--kerb] [-c|--cm] [-e|--cm-exit] [-s|--cm-status] [lxhost]"
            echo
            echo "LXPlus ssh connection manager."
            echo "A persistent background ControlMaster (CM) session will be initialized for each ssh target."
            echo
            echo "Options:"
            echo "  -u, --user USER         Use the specified USER instead of \$CERN_USERNAME (or \$USER)."
            echo "  -p, --p1-proxy          Pipe proxy to P1 (atlasgw.cern.ch) using port 3128."
            echo "  -v, --vnc, --vnc=OFFSET Set VNC proxy on port 5900+OFFSET, using OFFSET=7 by default if not provided."
            echo "  -b, --background        Keep the ssh connection in the background without a shell (e.g. for port forwarding); same as using 'ssh -fN'."
            echo "  -k, --kerb              Open Kerberos token only using k5start, with the keytab located at \$HOME/.keytab."
            echo "  -c, --cm                Open SSH ControlMaster background session only."
            echo "  -e, --cm-exit, --cme    Exit SSH ControlMaster background session only."
            echo "  -E, --cm-exit-all       Exit all SSH ControlMaster background sessions only."
            echo "  -s, --cm-status, --cms  Show all valid SSH ControlMaster sessions only."
            echo "  -h, --help              Show this help message and exit."
            echo
            echo "The final argument is used to get the LXPlus host:"
            echo " + '': lxplus"
            echo " + '<NUM>': lxplus<NUM>"
            echo " + 'abm<NUM>' | 'b<NUM>: lxplus8s0<NUM>"
            echo " + 'arm': lxplus-arm"
            echo " + 'lxtunnel' | 'tunnel' | 'lxt' | 't': lxtunnel"
            echo
            echo "Examples:"
            echo "  lxp               → ssh -Y \$CERN_USERNAME@lxplus.cern.ch"
            echo "  lxp abm9          → ssh -Y \$CERN_USERNAME@lxplus8s09.cern.ch"
            echo "  lxp -u alice abm9 → ssh -Y alice@lxplus8s09.cern.ch"
            exit 0
            ;;
        --) # stop parsing
            shift
            break
            ;;
        -*)
            echo "lxp: unknown option: $1" >&2
            exit 1
            ;;
        *)
            if [[ -n "$lxhost_arg" ]]; then
                echo "lxp: unknown argument: $1" >&2
                exit 1
            fi
            lxhost_arg="$1"
            shift
            ;;
    esac
done

# Check cmd line options
if [[ -n "$lxhost_arg" && "$do_kerb_only" = true ]]; then
    echo "lxp: cannot specify lxhost argument if using --kerb" >&2
    exit 1
fi

if [[ ("$do_kerb_only" = true || "$do_cm_start_only" = true || "$do_cm_exit_only" = true || "$do_cm_status_only" = true) && ("$do_atlasgw_proxy" = true || "$do_vnc_proxy" = true) ]]; then
    echo "lxp: cannot use both --kerb/--cm/--cm-exit/--cm-status and --p1-proxy/--vnc simultaneously" >&2
    exit 1
fi

if [[ "$do_cm_start_only" = true && "$do_cm_exit_only" = true ]]; then
    echo "lxp: cannot use both --cm and --cm-exit simultaneously" >&2
    exit 1
fi


#------------------------------------------
# Initialize kerberos token
#------------------------------------------
# Unless we're using --kerb, first check if we have a valid ticket already
if [[ "$do_cm_exit_only" = false && "$do_cm_status_only" = false && ( "$do_kerb_only" = true || $(kerb -c 2>/dev/null) != "There is a valid Kerberos ticket already for "* ) ]]; then
    kerb -r $user

    if [[ "$do_kerb_only" = true ]]; then
        exit 0
    fi
fi


#------------------------------------------
# Get target user/host
#------------------------------------------
target="${user}@$(lxhost $lxhost_arg)"


#------------------------------------------
# Get ControlMaster directory path
#------------------------------------------
if [[ ! -z "$CM_SOCKET_DIR" ]]; then
    CM_PATH="$CM_SOCKET_DIR"
elif [[ "$(uname)" == "Linux" ]]; then
    CM_PATH="/run/user/$(id -u)"
elif [[ "$(uname)" == "Darwin" ]]; then
    CM_PATH="$HOME/.ssh"
fi


#------------------------------------------
# Get all open ControlMaster sessions
#------------------------------------------
# Avoid literal * if no files match
shopt -s nullglob
cms=()
for f in "$CM_PATH"/*; do
    if [[ $(basename "$f") =~ ^([^:@]+@[^:@]+):[0-9]+$ ]]; then
        cms+=("${BASH_REMATCH[1]}")
    fi
done


#------------------------------------------
# Show list of open ControlMaster sessions
#------------------------------------------
if [[ "$do_cm_status_only" = true ]]; then
    if [[ "${#cms[@]}" == 0 ]]; then
        echo "No open SSH ControlMaster sessions"
    else
        echo "Open SSH ControlMaster sessions:"
        printf -- '- %s\n' "${cms[@]}"
    fi
    exit 0
fi


#------------------------------------------
# ControlMaster session exit
#------------------------------------------
# First check if the CM link exists
if [[ "$do_cm_exit_only" = true ]]; then
    if [[ "$do_cm_exit_all_only" = true ]]; then
        if [[ "${#cms[@]}" == 0 ]]; then
            echo "lxp: no ssh ControlMaster sessions to exit" >&2
            exit 1
        fi

        for cm_session in "${cms[@]}"; do
            echo -n "${cm_session}: "
            ssh -O exit "$cm_session"
        done
        exit 0

    else
        for cm_session in "${cms[@]}"; do
            if [[ "$cm_session" == "$target" ]]; then
                ssh -O exit "$cm_session"
                exit 0
            fi
        done

        echo "lxp: no ssh ControlMaster session for $target" >&2
        exit 1
    fi
fi


#------------------------------------------
# ControlMaster session initialization
#------------------------------------------
if [[ ! -e "$CM_PATH/$target:22" ]]; then
    sshcm-otp "$target" "$(pass otp "cern-${user}")"

    if [[ "$do_cm_start_only" = true ]]; then
        exit 0
    fi
fi


#------------------------------------------
# Main ssh session
#------------------------------------------
args=()

if [[ "$do_atlasgw_proxy" = true ]]; then
    args+=("-L3128:atlasgw.cern.ch:3128")
fi

if [[ "$do_vnc_proxy" = true ]]; then
    args+=("-L${vnc_port}:localhost:${vnc_port}")
fi

if [[ "$do_bkg" = true ]]; then
    # -x to disable X11 forwarding
    # -f to fork the connection to the background
    # -N to not spawn a shell in the remote host
    args+=("-xfN")
else
    # -Y to enable trusted X11 forwarding
    args+=("-Y")
fi

args+=("$target")

# Initialize ssh connection
ssh "${args[@]}"

exit 0
